apiVersion: v1
kind: ConfigMap
metadata:
  name: search-app-config  # Specifies the name of the ConfigMap
  namespace: distributed-systems  # Specifies the namespace in which the ConfigMap is created
immutable: false  # Indicates that the ConfigMap can be modified
data:
  MONGO_DB: spotify
  MONGO_HOST: mongo-svc.mongo.svc.cluster.local
  MONGO_USERNAME: adminuser
  MONGO_PASSWORD: password123
  MONGO_PORT: "27017"
  KAFKA_BOOTSTRAP_SERVERS: kafka-svc.kafka.svc.cluster.local:9092