apiVersion: v1
kind: ConfigMap
metadata:
  name: server-2-config  # Specifies the name of the ConfigMap
  namespace: distributed-systems  # Specifies the namespace in which the ConfigMap is created
immutable: false  # Indicates that the ConfigMap can be modified
data:
  KAFKA_HOSTS: kafka-svc.kafka.svc.cluster.local:9092
  #MONGO_HOST: mongo-svc.mongo.svc.cluster.local:27017
  MONGO_HOST: mongodb://adminuser:password123@mongo-svc.mongo.svc.cluster.local:27017
  MONGO_USERNAME: adminuser
  MONGO_PASSWORD: password123