apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: kafka
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-svc:2181"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:29092,PLAINTEXT_INTERNAL://kafka-svc.kafka.svc.cluster.local:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"

  # KAFKA_PORT: "9092"  
  # KAFKA_ADVERTISED_HOST_NAME: "kafka-svc.kafka.svc.cluster.local"
  # KAFKA_ZOOKEEPER_CONNECT: "zookeeper-svc:2181"
  # KAFKA_ADVERTISED_PORT : "9092"
