apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        kubernetes.io/hostname: srinivas
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.0.1
          ports:
            - containerPort: 2181
          envFrom:
            - configMapRef:
                name: zookeeper-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

--- 

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker-1
  namespace: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      nodeSelector:
        kubernetes.io/hostname: blackbox
      containers:
      - name: broker
        image: confluentinc/cp-kafka:7.0.1
        ports:
          - containerPort: 9092
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
        envFrom:
          - configMapRef:
              name: kafka-config
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "500m"

# ---

# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: kafka-broker-2
#   namespace: kafka
#   labels:
#     app: kafka
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka-broker-2
#   template:
#     metadata:
#       labels:
#         app: kafka-broker-2
#     spec:
#       nodeSelector:
#         kubernetes.io/hostname: blackbox
#       containers:
#       - name: broker
#         image: confluentinc/cp-kafka:7.0.1
#         ports:
#           - containerPort: 9092
#         env:
#           - name: KAFKA_BROKER_ID
#             value: "2"
#         envFrom:
#           - configMapRef:
#               name: kafka-config
#         resources:
#           requests:
#             memory: "2Gi"
#             cpu: "500m"
#           limits:
#             memory: "2Gi"
#             cpu: "500m"

