apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: kafka
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

--- 

apiVersion: v1 
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka-broker-1
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092